name: Test colors
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Launch shell script
        run: |
          echo "Running test script..."
          chmod +x ./test.sh
          export TERM=xterm-color
          ./test.sh
        shell: bash
